### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by alhuber1502** [jrladd/endlessmonument#1]
I imagine today's line shouldn't read:

undefined
Ye learned sisters which have oftentimes

**Comment by jrladd** [comment]
It definitely shouldn't! Thanks for noting this, I'll take a look.

**Comment by jrladd** [comment]
Since Spenser's year starts on March 1st, any days in January or February were getting treated as negative values. I'm pushing a fix for this now. Thanks again, @alhuber1502!
